name: Test
on: push
jobs:
  test:
    services:
      redis:
        image: 'redislabs/redismod'
        ports:
          - '6379:6379'
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: prismy-session
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
        ports:
          - 5432:5432
    container: node:18
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: Test
        run: npm test
